name: Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust

    - name: Run locust load test
      run: |
        python tests/products_test.py

    - name: Upload load test results
      uses: actions/upload-artifact@v2
      with:
        name: load-test-stats
        path: load_test_stats/

      
