name: Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install
          npm run install-dependencies

    - name: Free ports 8089 and 8090
      run: |
            for port in 8089 8090; do
              if lsof -i :$port; then
                echo "Killing process on port $port"
                kill -9 $(lsof -t -i :$port)
              else
                echo "No process on port $port"
              fi
            done
  
    - name: Run locust UI
      env:
          PYTHONPATH: .
      run: |
          npm start
  
    - name: Run locust tests
      env:
          PYTHONPATH: .
      run: |
          python tests/products_test.py

      
