global:
  scrape_interval: 15s
scrape_configs:
  - job_name: locust
    static_configs:
      - targets:
          - 'localhost:8000'
    
  - url: 'https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push'
    basic_auth:
      username: 1710965
      password: >-
        lc_eyJvIjoiMTE4NDQ3OSIsIm4iOiJzdGFjay05OTc2MDMtaG0tcmVhZC1hZG1pbiIsImsiOiJDWnEyMDk2bThCOXczMzN2QkNQZ1o0TmQiLCJtIjp7InIiOiJwcm9kLXVzLWVhc3QtMCJ9fQ==
   
